# This is a basic workflow to help you get started with Actions

name: build-commit
concurrency: build-commit

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # see https://github.com/actions/checkout#usage for reference
      - uses: actions/checkout@v3
        with:
          ref: build
          fetch-depth: 0
      - run: |
          git fetch --no-tags origin main
          git checkout -b main origin/main
          git switch build

      - run: git log --oneline

      - run: sudo apt-get update

      - name: apt stuff
        uses: tecoli-com/actions-use-apt-tools@v0
        with:
          tools: graphviz texlive texlive-latex-extra

      - name: Install lua
        uses: leafo/gh-actions-lua@v9

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.3.0

      - name: install luarocks deps
        run: |
          luarocks install lua-term
          luarocks install luaprompt
          luarocks install lua_cliargs

      - name: ls
        run: ls -al ./*

      - run: git branch
      - run: git log --branches --remotes --tags --graph --pretty=oneline --abbrev-commit --date=relative --decorate

      - name: update on main
        run: |
          git config --global user.name "Updater"
          git merge --no-ff main

      - name: restore modification times
        run: ./restore-ts.sh

      - run: git branch
      - run: git log --branches --remotes --tags --graph --pretty=oneline --abbrev-commit --date=relative --decorate

      - name: ls
        run: ls -al ./*

      - name: Build results files
        run: |
          make -f Makefile.action all
          make -f Makefile.action stats.pdf

      - name: ls
        run: ls -al ./*

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Built results
          branch: build
