# This is a basic workflow to help you get started with Actions

name: build-commit

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # see https://github.com/actions/checkout#usage for reference
      - uses: actions/checkout@v3
        with:
          ref: build
          fetch-depth: 0
      - run: |
          git fetch --no-tags --depth=1 origin main
          git checkout -b main
          git checkout build

      - run: git log --oneline
      - name: restore modification times
        run: ./restore-ts.sh
        

      - name: Install graphviz
        run: |
          sudo apt-get update
          sudo apt install graphviz

      # Runs multiple commands using the runners shell
      # - name: install lua
      #   run: |
      #     curl -R -O https://www.lua.org/ftp/lua-5.4.4.tar.gz
      #     tar zxf lua-5.4.4.tar.gz
      #     cd lua-5.4.4
      #     make all
      #     sudo make install
      #     ls -al /usr/local/bin/

      - name: Install lua
        uses: leafo/gh-actions-lua@v9

      - name: Install LuaRocks
        # You may pin to the exact commit or the version.
        uses: leafo/gh-actions-luarocks@v4.3.0

      - name: install luarocks deps
        run: |
          luarocks install lua-term
          luarocks install luaprompt
          luarocks install lua_cliargs

      - name: update on master
        run: |
          git rebase main

      - name: ls
        run: ls -al ./*

      # Runs a single command using the runners shell
      - name: Build results files
        run: make all
        
      - name: ls
        run: ls -al ./*
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Built results
          push_options: --force
          branch: build
